export const state = {
  user: null,
  characters: [],
  voices: [],
  active: null,
  activeConversation: null,
  selectedConversations: {},
  conversations: [],
  messages: [],
  voiceConversations: [],
  activeVoiceConversation: null,
  voiceMessages: [],
  authMode: "login",
  conversation: null,
  listening: false,
  sending: false,
};